"use client"

import { motion } from "framer-motion"
import { FileText, Download, BookOpen, Code, MessageSquare, ClipboardCheck } from "lucide-react"

const notesSections = [
  { icon: BookOpen, label: "Summary", content: "RAG (Retrieval-Augmented Generation) combines external knowledge retrieval with LLM generation to produce accurate, grounded responses." },
  { icon: Code, label: "Key Concepts", items: ["Vector embeddings", "Similarity search", "Context window management", "Chunking strategies", "Re-ranking"] },
  { icon: MessageSquare, label: "Interview Questions", items: ["How does RAG differ from fine-tuning?", "What are the tradeoffs of different chunking strategies?", "How do you evaluate RAG pipeline quality?"] },
]

export function SmartNotesSection() {
  return (
    <section className="py-20" id="notes">
      <div className="max-w-[1200px] mx-auto px-5">
        <div className="grid lg:grid-cols-2 gap-16 items-start">
          {/* Left — Content */}
          <motion.div
            initial={{ opacity: 0, y: 12 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
          >
            <div className="flex items-center gap-2 mb-4">
              <div className="w-6 h-6 rounded-md bg-accent/15 flex items-center justify-center">
                <FileText className="w-3.5 h-3.5 text-accent" />
              </div>
              <span className="text-mono text-[11px] text-foreground-subtle uppercase tracking-wider">
                Section 04
              </span>
            </div>

            <h2 className="text-display text-3xl sm:text-4xl mb-3 leading-[1.15] max-w-md">
              AI-Generated Notes That{" "}
              <span className="text-accent">Actually Help</span>
            </h2>

            <p className="text-foreground-muted text-[15px] leading-relaxed mb-8 max-w-md">
              Every roadmap concept comes with structured notes — summaries, key concepts, 
              examples, interview prep, and revision checklists. Generated by AI, tailored to your level.
            </p>

            <div className="flex flex-wrap gap-2">
              {["Summary", "Key Concepts", "Examples", "Interview Prep", "Revision Sheet"].map((tag) => (
                <span
                  key={tag}
                  className="text-mono text-[10px] px-2.5 py-1 rounded-full border border-border bg-surface-1 text-foreground-subtle"
                >
                  {tag}
                </span>
              ))}
            </div>
          </motion.div>

          {/* Right — Notes Preview */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
          >
            <div className="surface-card overflow-hidden">
              {/* Header */}
              <div className="px-5 py-3.5 border-b border-border flex items-center justify-between">
                <div>
                  <div className="text-[13px] text-emphasis text-foreground">RAG Systems</div>
                  <div className="text-mono text-[10px] text-foreground-subtle">RD-004 · AI-generated · 8 min read</div>
                </div>
                <button className="flex items-center gap-1.5 px-2.5 py-1.5 rounded-md bg-surface-2 border border-border hover:border-accent/30 transition-colors">
                  <Download className="w-3 h-3 text-foreground-subtle" />
                  <span className="text-mono text-[10px] text-foreground-subtle">Export</span>
                </button>
              </div>

              {/* Content */}
              <div className="p-5 space-y-5">
                {notesSections.map((section, i) => (
                  <motion.div
                    key={section.label}
                    initial={{ opacity: 0, y: 8 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ delay: 0.2 + i * 0.1 }}
                  >
                    <div className="flex items-center gap-2 mb-2">
                      <section.icon className="w-3.5 h-3.5 text-accent" />
                      <span className="text-mono text-[11px] text-foreground-subtle uppercase tracking-wider">
                        {section.label}
                      </span>
                    </div>
                    {section.content && (
                      <p className="text-[13px] text-foreground-muted leading-relaxed pl-5.5">
                        {section.content}
                      </p>
                    )}
                    {section.items && (
                      <ul className="pl-5.5 space-y-1.5">
                        {section.items.map((item) => (
                          <li key={item} className="flex items-start gap-2 text-[13px] text-foreground-muted">
                            <span className="text-foreground-subtle mt-1.5">·</span>
                            {item}
                          </li>
                        ))}
                      </ul>
                    )}
                  </motion.div>
                ))}

                {/* Revision checklist */}
                <motion.div
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.5 }}
                >
                  <div className="flex items-center gap-2 mb-2">
                    <ClipboardCheck className="w-3.5 h-3.5 text-accent" />
                    <span className="text-mono text-[11px] text-foreground-subtle uppercase tracking-wider">
                      Revision Checklist
                    </span>
                  </div>
                  <div className="pl-5.5 space-y-1.5">
                    {["Understand vector similarity metrics", "Implement basic RAG pipeline", "Compare chunking strategies"].map((item, i) => (
                      <label key={item} className="flex items-center gap-2 text-[13px] text-foreground-muted cursor-pointer">
                        <div className={`w-3.5 h-3.5 rounded-sm border ${i === 0 ? "bg-accent border-accent" : "border-border"} flex items-center justify-center`}>
                          {i === 0 && <span className="text-[8px] text-accent-foreground">✓</span>}
                        </div>
                        <span className={i === 0 ? "line-through text-foreground-subtle" : ""}>{item}</span>
                      </label>
                    ))}
                  </div>
                </motion.div>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  )
}
